baseURL = "cuglilong.github.io"
# [en, zh-cn, fr, ...] 设置默认的语言
defaultContentLanguage = "zh-cn"
# 网站语言，仅在这里 CN 大写
languageCode = "zh-CN"
# 是否包括中日韩文字
hasCJKLanguage = true
# 网站标题
title = "Long's blog"

# 更改使用 Hugo 构建网站时使用的默认主题
theme = "FixIt"

[params]
  # FixIt 更改 | 0.2.0 FixIt 主题版本
  version = "0.2.X"
  # 网站描述
  description = "Long blog"
  # 网站关键词
  keywords = ["Theme", "Hugo"]
  # 网站默认主题样式 ("light", "dark", "auto")
  defaultTheme = "auto"
  # 公共 git 仓库路径，仅在 enableGitInfo 设为 true 时有效
  gitRepo = ""
  # FixIt 新增 | 0.1.1 哪种哈希函数用来 SRI, 为空时表示不使用 SRI
  # ("sha256", "sha384", "sha512", "md5")
  fingerprint = ""
  # FixIt 新增 | 0.2.0 日期格式
  dateFormat = "2006-01-02"
  # 网站图片，用于 Open Graph 和 Twitter Cards
  images = ["/logo.png"]
  # FixIt 新增 | 0.2.12 开启 PWA 支持
  enablePWA = true

# FixIt 新增 | 0.2.0 应用图标配置
  [params.app]
    # 当添加到 iOS 主屏幕或者 Android 启动器时的标题，覆盖默认标题
    title = "FixIt"
    # 是否隐藏网站图标资源链接
    noFavicon = false
    # 更现代的 SVG 网站图标，可替代旧的 .png 和 .ico 文件
    svgFavicon = ""
    # Safari 图标颜色
    iconColor = "#5bbad5"
    # Windows v8-10 磁贴颜色
    tileColor = "#da532c"
    # FixIt 更改 | 0.2.12 Android 浏览器主题色
    [params.app.themeColor]
      light = "#ffffff"
      dark = "#252627"
    
  [outputs]
  home = ["HTML", "RSS", "JSON"]

  # FixIt 新增 | 0.2.0 搜索配置
  [params.search]
    enable = true
    # 搜索引擎的类型 ("lunr", "algolia")
    type = "lunr"
    # 文章内容最长索引长度
    contentLength = 4000
    # 搜索框的占位提示语
    placeholder = ""
    # FixIt 新增 | 0.2.1 最大结果数目
    maxResultLength = 10
    # FixIt 新增 | 0.2.3 结果内容片段长度
    snippetLength = 50
    # FixIt 新增 | 0.2.1 搜索结果中高亮部分的 HTML 标签
    highlightTag = "em"
    # FixIt 新增 | 0.2.4 是否在搜索索引中使用基于 baseURL 的绝对路径
    absoluteURL = false
    [params.search.algolia]
      index = ""
      appID = ""
      searchKey = ""
  
  # 页面头部导航栏配置
  [params.header]
    # 桌面端导航栏模式 ("sticky", "normal", "auto")
    #desktopMode = "sticky"
    # 移动端导航栏模式 ("sticky", "normal", "auto")
    #mobileMode = "auto"
    # FixIt 新增 | 0.2.0 页面头部导航栏标题配置
    [params.header.title]
      # LOGO 的 URL
      #logo = ""
      # 标题名称
      name ="Long's blog"
      # 你可以在名称（允许 HTML 格式）之前添加其他信息，例如图标
      pre = ""
      # 你可以在名称（允许 HTML 格式）之后添加其他信息，例如图标
      #post = ""
      # FixIt 新增 | 0.2.5 是否为标题显示打字机动画
      typeit = false
    # FixIt 新增 | 0.2.12 页面头部导航栏副标题配置
    [params.header.subtitle]
      # 副标题名称
      #name = "Welcome"
      # 是否为副标题显示打字机动画
      #typeit = true
  
  # 页面底部信息配置
  [params.footer]
    enable = true
    # FixIt 新增 | 0.2.0 自定义内容（支持 HTML 格式）
    custom = ''
    # FixIt 新增 | 0.2.0 是否显示 Hugo 和主题信息
    hugo = true
    # FixIt 新增 | 0.2.0 是否显示版权信息
    copyright = true
    # FixIt 新增 | 0.2.0 是否显示作者
    author = true
    # 网站创立年份
    since = 2018
    # FixIt 新增 | 0.2.12 公网安备信息，仅在中国使用（支持 HTML 格式）
    gov = ""
    # FixIt 更改 | 0.2.12 ICP 备案信息，仅在中国使用（支持 HTML 格式）
    icp = ""
    # 许可协议信息（支持 HTML 格式）
    license = '<a rel="license external nofollow noopener noreffer" href="https://creativecommons.org/licenses/by-nc/4.0/" target="_blank">CC BY-NC 4.0</a>'

  # FixIt 新增 | 0.2.0 Section（所有文章）页面配置
  [params.section]
    # section 页面每页显示文章数量
    paginate = 20
    # 日期格式（月和日）
    dateFormat = "01-02"
    # RSS 文章数目
    rss = 10
    # FixIt 新增 | 0.2.13 最近更新文章设置
    [params.section.recentlyUpdated]
      enable = false
      rss = false
      days = 30
      maxCount = 10  

  # FixIt 新增 | 0.2.0 List（目录或标签）页面配置
  [params.list]
    # list 页面每页显示文章数量
    paginate = 20
    # 日期格式（月和日）
    dateFormat = "01-02"
    # RSS 文章数目
    rss = 10

  # 主页配置
  [params.home]
    # FixIt 新增 | 0.2.0 RSS 文章数目
    rss = 10
    # 主页个人信息
    [params.home.profile]
      enable = true
      # FixIt 新增 | 0.2.13 选择使用 Gravatar 源站或其他镜像站，若留空则为默认的 "www.gravatar.com"
      gravatarSite = ""
      # Gravatar 邮箱，用于优先在主页显示的头像
      gravatarEmail = ""
      # 主页显示头像的 URL
      #avatarURL = "/images/avatar.png"
      # FixIt 更改 | 0.2.7 主页显示的网站标题（支持 HTML 格式）
      title = ""
      # 主页显示的网站副标题
      subtitle = "Welcome"
      # 是否为副标题显示打字机动画
      typeit = true
      # 是否显示社交账号
      social = true
      # FixIt 新增 | 0.2.0 免责声明（支持 HTML 格式）
      disclaimer = ""
    # 主页文章列表
    [params.home.posts]
      enable = true
      # 主页每页显示文章数量
      paginate = 8

  # 作者的社交信息设置
  [params.social]
    GitHub = "cuglilong"
    #Linkedin = ""
    Twitter = "xxxx"
    Email = "cuglilong@163.com"
    #CSDN = "ucaslilong"
  
  # FixIt 更改 | 0.2.0 文章页面配置
  [params.page]
    # FixIt 新增 | 0.2.0 是否在主页隐藏一篇文章
    hiddenFromHomePage = false
    # FixIt 新增 | 0.2.0 是否在搜索结果中隐藏一篇文章
    hiddenFromSearch = false
    # FixIt 新增 | 0.2.0 是否使用 twemoji
    twemoji = false
    # 是否使用 lightgallery
    lightgallery = false
    # FixIt 新增 | 0.2.0 是否使用 ruby 扩展语法
    ruby = true
    # FixIt 新增 | 0.2.0 是否使用 fraction 扩展语法
    fraction = true
    # FixIt 新增 | 0.2.0 是否使用 fontawesome 扩展语法
    fontawesome = true
    # 许可协议信息（支持 HTML 格式）
    #license = '<a rel="license external nofollow noopener noreffer" href="https://creativecommons.org/licenses/by-nc/4.0/" target="_blank">CC BY-NC 4.0</a>'
    # 是否在文章页面显示原始 Markdown 文档链接
    linkToMarkdown = true
    # FixIt 新增 | 0.2.4 是否在 RSS 中显示全文内容
    rssFullText = false
    # FixIt 新增 | 0.2.13 页面样式 ("normal", "wide", ...)
    pageStyle = "normal"
    # FixIt 新增 | 0.2.0 目录配置
    [params.page.toc]
      # 是否使用目录
      #enable = true
      # FixIt 新增 | 0.2.9 是否保持使用文章前面的静态目录
      #keepStatic = true
      # 是否使侧边目录自动折叠展开
      #auto = true
      # FixIt 新增 | 0.2.13 目录位置 ("left", "right")
      #position = "left"
    # FixIt 新增 | 0.2.13 在文章开头显示提示信息，提醒读者文章内容可能过时
    [params.page.expirationReminder]
      enable = false
      # 如果文章最后更新于这天数之前，显示提醒
      reminder = 90
      # 如果文章最后更新于这天数之前，显示警告
      warning = 180
      # 如果文章到期是否关闭评论
      closeComment = false
    # FixIt 新增 | 0.2.0 代码配置
    [params.page.code]
      # 是否显示代码块的复制按钮
      copy = true
      # FixIt 新增 | 0.2.13 是否显示代码块的编辑按钮
      edit = true
      # 默认展开显示的代码行数
      maxShownLines = 10
    # FixIt 更改 | 0.2.0 KaTeX 数学公式 (https://katex.org)
    [params.page.math]
      enable = true
      # 默认块定界符是 $$ ... $$ 和 \\[ ... \\]
      blockLeftDelimiter = ""
      blockRightDelimiter = ""
      # 默认行内定界符是 $ ... $ 和 \\( ... \\)
      inlineLeftDelimiter = ""
      inlineRightDelimiter = ""
      # KaTeX 插件 copy_tex
      copyTex = true
      # KaTeX 插件 mhchem
      mhchem = true
    # FixIt 新增 | 0.2.0 Mapbox GL JS 配置 (https://docs.mapbox.com/mapbox-gl-js)
    [params.page.mapbox]
      # Mapbox GL JS 的 access token
      accessToken = ""
      # 浅色主题的地图样式
      lightStyle = "mapbox://styles/mapbox/light-v9"
      # 深色主题的地图样式
      darkStyle = "mapbox://styles/mapbox/dark-v9"
      # 是否添加 NavigationControl
      navigation = true
      # 是否添加 GeolocateControl
      geolocate = true
      # 是否添加 ScaleControl
      scale = true
      # 是否添加 FullscreenControl
      fullscreen = true
    # FixIt 更改 | 0.2.0 文章页面的分享信息设置
    [params.page.share]
      enable = false
      Twitter = true
      Facebook = true
      Linkedin = false
      Whatsapp = true
      Pinterest = false
      Tumblr = false
      HackerNews = false
      Reddit = false
      VK = false
      Buffer = false
      Xing = false
      Line = true
      Instapaper = false
      Pocket = false
      Digg = false
      Stumbleupon = false
      Flipboard = false
      Weibo = true
      Renren = false
      Myspace = true
      Blogger = true
      Baidu = false
      Odnoklassniki = false
      Evernote = true
      Skype = false
      Trello = false
      Mix = false
    # FixIt 更改 | 0.2.13 评论系统设置
    [params.page.comment]
      enable = true
      # FixIt 新增 | 0.2.13 Artalk 评论系统设置 (https://artalk.js.org/)
      [params.page.comment.artalk]
        enable = false
        server = "https://yourdomain/api/"
        site = "默认站点"
        placeholder = ""
        noComment = ""
        sendBtn = ""
        editorTravel = true
        flatMode = 'auto'
        maxNesting = 3
        # 当 `params.page.lightgallery` 启用时生效
        lightgallery = false
      # Disqus 评论系统设置 (https://disqus.com)
      [params.page.comment.disqus]
        # FixIt 新增 | 0.1.1
        enable = true
        # Disqus 的 shortname，用来在文章中启用 Disqus 评论系统
        shortname = "cuglilong"
      # Gitalk 评论系统设置 (https://github.com/gitalk/gitalk)
      [params.page.comment.gitalk]
        # FixIt 新增 | 0.1.1
        enable = false
        owner = ""
        repo = ""
        clientId = ""
        clientSecret = ""
      # Valine 评论系统设置 (https://github.com/xCss/Valine)
      [params.page.comment.valine]
        enable = false
        appId = ""
        appKey = ""
        placeholder = ""
        avatar = "mp"
        meta= ""
        pageSize = 10
        lang = ""
        visitor = true
        recordIP = true
        highlight = true
        enableQQ = false
        serverURLs = ""
        # FixIt 新增 | 0.2.6 emoji 数据文件名称，默认是 "google.yml"
        # ("apple.yml", "google.yml", "facebook.yml", "twitter.yml")
        # 位于 "themes/FixIt/assets/data/emoji/" 目录
        # 可以在你的项目下相同路径存放你自己的数据文件：
        # "assets/data/emoji/"
        emoji = ""
        commentCount = true # FixIt 新增 | 0.2.13
      # FixIt 新增 | 0.2.13 Waline 评论系统设置 (https://waline.js.org)
      [params.page.comment.waline]
        enable = false
        serverURL = ""
        visitor = false
        emoji = ['https://cdn.jsdelivr.net/gh/walinejs/emojis/weibo']
        meta = ['nick', 'mail', 'link']
        requiredMeta = []
        login = 'enable'
        wordLimit = 0
        pageSize = 10
        uploadImage = false
        highlight = true
        mathTagSupport = false
        commentCount = false
      # Facebook 评论系统设置 (https://developers.facebook.com/docs/plugins/comments)
      [params.page.comment.facebook]
        enable = false
        width = "100%"
        numPosts = 10
        appId = ""
        languageCode = "zh_CN"
      # FixIt 新增 | 0.2.0 Telegram Comments 评论系统设置 (https://comments.app)
      [params.page.comment.telegram]
        enable = false
        siteID = ""
        limit = 5
        height = ""
        color = ""
        colorful = true
        dislikes = false
        outlined = false
      # FixIt 新增 | 0.2.0 Commento 评论系统设置 (https://commento.io)
      [params.page.comment.commento]
        enable = false
      # FixIt 新增 | 0.2.5 Utterances 评论系统设置 (https://utteranc.es)
      [params.page.comment.utterances]
        enable = false
        # owner/repo
        repo = ""
        issueTerm = "pathname"
        label = ""
        lightTheme = "github-light"
        darkTheme = "github-dark"
      # FixIt 新增 | 0.2.13 Twikoo 评论系统设置 (https://twikoo.js.org/)
      [params.page.comment.twikoo]
        enable = false
        envId = ""
        region = ""
        path = ""
        visitor = true
        commentCount = true
        # 当 `params.page.lightgallery` 启用时生效
        lightgallery = false
    # FixIt 新增 | 0.2.7 第三方库配置
    [params.page.library]
      [params.page.library.css]
        # someCSS = "some.css"
        # 位于 "assets/"
        # 或者
        # someCSS = "https://cdn.example.com/some.css"
      [params.page.library.js]
        # someJavascript = "some.js"
        # 位于 "assets/"
        # 或者
        # someJavascript = "https://cdn.example.com/some.js"
    # FixIt 更改 | 0.2.10 页面 SEO 配置
    [params.page.seo]
      # 图片 URL
      images = []
      # 出版者信息
      [params.page.seo.publisher]
        name = ""
        logoUrl = ""
  
  # FixIt 新增 | 0.2.12 不蒜子统计
  [params.ibruce]
    enable = true
    # 在文章中开启
    enablePost = true
    # 网站创立时间 例：'2019-02-03T19:30:34+08:00'
    siteTime = ''

  # FixIt 新增 | 0.2.0 网站分析配置
  [params.analytics]
    enable = false
    # Google Analytics
    [params.analytics.google]
      id = ""
      # 是否匿名化用户 IP
      anonymizeIP = true
    # Fathom Analytics
    [params.analytics.fathom]
      id = ""
      # 自行托管追踪器时的主机路径
      server = ""

[menu]
  [[menu.main]]
    identifier = "posts"
    # 你可以在名称（允许 HTML 格式）之前添加其他信息，例如图标
    pre = ""
    # 你可以在名称（允许 HTML 格式）之后添加其他信息，例如图标
    post = ""
    name = "文章"
    url = "/posts/"
    # 当你将鼠标悬停在此菜单链接上时，将显示的标题
    title = ""
    weight = 1
  [[menu.main]]
    identifier = "tags"
    pre = ""
    post = ""
    name = "标签"
    url = "/tags/"
    title = ""
    weight = 2
  [[menu.main]]
    identifier = "categories"
    pre = ""
    post = ""
    name = "分类"
    url = "/categories/"
    title = ""
    weight = 3

# Hugo 解析文档的配置
[markup]
  # 语法高亮设置 (https://gohugo.io/content-management/syntax-highlighting)
  [markup.highlight]
    # false 是必要的设置 (https://github.com/Lruihao/FixIt/issues/43)
    noClasses = false
   # 目录设置
  [markup.tableOfContents]
    #startLevel = 2
    #endLevel = 6


# 作者配置
[author]
  name = "cuglilong"
  email = "cuglilong@163.com"
  link = ""

# 网站地图配置
[sitemap]
  changefreq = "weekly"
  filename = "sitemap.xml"
  priority = 0.5
